baseurl: "http://rackerlabs.github.io/repose"
include: ["_images", "_includes", "_javascripts", "_stylesheets"]
exclude: ["README.md", "Gruntfile.js", "changelog.md", "Gemfile", "Gemfile.lock", "node_modules", "bower_components", "scss", "config.rb", "package.json", "LICENSE-MIT", "bower.json"]
markdown: kramdown
safe: false
